blog/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url 
from blog.views import ArticlePublishView, ArticleListView, ArticleEditView

urlpatterns = patterns('blog.views',
    url(r'^$', ArticleListView.as_view(), name='blog_index'),
    url(r'^(?P<id>\d+)/$', 'detail', name='blog_detail'),
    url(r'^(?P<id>\d+)/edit$', ArticleEditView.as_view(), name='blog_edit'),
    url(r'^user/(?P<username>\w+)/$', 'blog_home', name='blog_home' ),
    url(r'^article/publish$', ArticlePublishView.as_view(), name="article_publish"),
    url(r'^post/list/$', 'post_list', name="post_list"),
    url(r'^del/(?P<id>\d+)/$', 'blog_del', name='blog_del'),
    
)

fairy/urls.py
from django.conf.urls import patterns, include, url
from fairy import settings
from django.contrib import admin
from django.conf.urls.static import static
import forum

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fairy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('forum.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^user/', include('account.urls')),
    url(r'^api/forum/', include(forum.urls.api_urlpatterns)),
    url(r'^panel/', include('panel.urls', namespace='panel', app_name='panel')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.conf.urls import patterns, include, url


api_urlpatterns = patterns('forum.api',
    url(r'^topic/(?P<topic_id>\d+)/$', 'topic_api', name='topic_api'),
    url(r'^topics/$', 'topics_api', name='topics_api'),
    url(r'^post/(?P<post_id>\d+)/$', 'post_api', name='post_api'),
    url(r'^/simditor-upload/$', 'simditor_upload', name='simditor_upload'),
)


urlpatterns = patterns('forum.views',
    url(r'^BBS/$', 'index', name='index'),
    url(r'^node/sort/$$' ,'node_sort', name='node_sort'),

    url(r'^topic/(?P<topic_id>\d+)/$', 'topic_view', name='topic_view'),
    url(r'^topic/(?P<topic_id>\d+)/reply/$', 'create_reply', name='create_reply'),
    url(r'^topic/(?P<topic_id>\d+)/append/$', 'add_appendix', name='add_appendix'),
    url(r'^topic/(?P<topic_id>\d+)/delete/$', 'del_topic', name='delete_topic'),
    url(r'^topic/(?P<topic_id>\d+)/edit/$', 'edit_topic', name='edit_topic'),
    url(r'^post/(?P<post_id>\d+)/delete/$', 'del_reply', name='delete_post'),
    url(r'^node/$', 'node_all', name='node_all'),
    url(r'^node/(?P<node_id>\d+)/$', 'node_view', name='node_view'),
    url(r'^node/(?P<node_id>\d+)/create/$', 'create_topic', name='create_topic'),
    url(r'^search/(?P<keyword>.*?)/$', 'search', name='search'),
    url(r'^recent/$', 'recent', name='recent'),
    url(r'^previewer/$', 'previewer', name='previewer'),
    url(r'^EvilFinder/$', 'develop', name='develop'),
    url(r'^$', 'Finder', name='Finder'),
    url(r'^FAQ/$', 'FAQ', name="FAQ"),
    
)

forum/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
import markdown
import re
from django.core.urlresolvers import reverse
# Create your models here.


class topic(models.Model):
    user = models.ForeignKey(User, related_name='topics')
    title = models.CharField(max_length=160)
    content = models.TextField(blank=True, null=True)
    content_rendered = models.TextField(blank=True, null=True)
    click = models.IntegerField(default=0)
    top = models.BooleanField(default=False)
    reply_count = models.IntegerField(default=0)
    node = models.ForeignKey('node', related_name='topics')
    time_created = models.DateTimeField(auto_now_add=True)
    last_replied = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)
    order = models.IntegerField(default=10)
    
    class Meta():
        ordering = ['order' ,'-time_created']

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            new = True
        else:
            new = False
        if not self.content:
            self.content = ''
        self.content_rendered = markdown.markdown(self.content, ['codehilite'],
                                                  safe_mode='escape')
        self.reply_count = self.post_set.filter(deleted=False).count()
        if self.reply_count:
            self.last_replied = self.post_set.filter(deleted=False).latest('time_created').time_created
        to = []
        for u in re.findall(r'@(.*?)\s', self.content_rendered):
            try:
                user = User.objects.get(username=u)
            except:
                pass
            else:
                to.append(user)
                self.content_rendered = re.sub('@%s' % (u),
                                               '@<a href="%s" class="mention">%s</a>'
                                               % (reverse('user_info',
                                                          kwargs={'user_id': user.id}),
                                                  u),
                                               self.content_rendered)
        super(topic, self).save(*args, **kwargs)
        if to and new:
            for t in to:
                m = mention()
                m.sender = self.user
                m.receiver = t
                m.topic = self
                m.save()

        if new:                     #若是新创建的帖子
            self.last_replied = self.time_created
            self.save()


class node(models.Model):
    title = models.CharField(max_length=12)
    description = models.TextField(blank=True)
    count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    topic = models.ForeignKey('topic')
    content = models.TextField()
    content_rendered = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)

    class Meta():
        ordering = ['time_created']

    def __unicode__(self):
        return str(self.id) + self.topic.title

    def save(self, *args, **kwargs):
        if not self.id:
            new = True
        else:
            new = False
        if not self.content:
            self.content = ''
        self.content_rendered = markdown.markdown(self.content, ['codehilite'],
                                                  safe_mode='escape')
        to = []
        for u in re.findall(r'@(.*?)\s', self.content_rendered):
            try:
                user = User.objects.get(username=u)
            except:
                pass
            else:
                to.append(user)
                self.content_rendered = re.sub('@%s' % (u),
                                               '@<a href="%s" class="mention">%s</a>'
                                               % (reverse('user_info',
                                                          kwargs={'user_id': user.id}),
                                                  u),
                                               self.content_rendered)
        super(post, self).save(*args, **kwargs)
        if to and new:
            for t in to:
                m = mention()
                m.sender = self.user
                m.receiver = t
                m.post = self
                m.topic = self.topic
                m.save()
        self.topic.save()


class notification(models.Model):
    sender = models.ForeignKey(User, related_name='sent_notifications')
    receiver = models.ForeignKey(User, related_name='received_nofitications')
    topic = models.ForeignKey(topic, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    read = models.BooleanField(default=True)
    time_created = models.DateTimeField(auto_now_add=True)


class mention(models.Model):
    sender = models.ForeignKey(User, related_name='sent_mentions')
    receiver = models.ForeignKey(User, related_name='received_mentions')
    post = models.ForeignKey(post, blank=True, null=True)
    topic = models.ForeignKey(topic, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    read = models.BooleanField(default=False)
    time_created = models.DateTimeField(auto_now_add=True)


class appendix(models.Model):                   #附言
    topic = models.ForeignKey(topic)
    time_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    content_rendered = models.TextField()

    def __unicode__(self):
        return self.topic.title + '-Appendix'

    def save(self, *args, **kwargs):
        if not self.content:
            self.content = ''
        self.content_rendered = markdown.markdown(self.content, ['codehilite'],
                                                  safe_mode='escape')
        super(appendix, self).save(*args, **kwargs)


# class AttentionUser(models.Model):
#     current_user = models.ForeignKey(User, related_name='main_user')               #当前用户
#     attention_user = models.ForeignKey(User, related_name='attention_user')        #当前用户所关注的用户

forum/templates/forum/HowToUse.html
{% extends 'base.html' %}
{% load i18n %}

{% block inside_row %}
<center><h2>网站使用指导及常见问题</h2></center>
<br>
<center>
<div class="table-responsive">
          
    <table class="table table-hover table-bordered">
        <tbody class="table-body">
            <tr>
                <td colspan="3" style="font-size:25px;text-align:center">网站FAQ</td>
            </tr>
            <tr class="table-head">
                <th>编号</th>
                <th>文章</th>
                <th>作者</th>
            </tr>
            <tr>
                <td>1</td>
                <td><a target="_blank" href="https://www.zybuluo.com/EvilFinder/note/380776">Finder社区使用FAQ</a></td>
                <td>EvilFinder</td>
            </tr>
           <tr>
                <td>2</td>
                <td><a target="_blank" href="https://www.zybuluo.com/EvilFinder/note/381111">Markdown使用简明教程</a></td>
                <td>EvilFinder</td>
            </tr>
           <tr>
                <td>3</td>
                <td><a target="_blank" href="https://www.zybuluo.com/EvilFinder/note/381414">常见问题及解决方案</a></td>
                <td>EvilFinder</td>
            </tr>
        </tbody>
        <tbody>
        
        </tbody>
    </table>

</div>
</center>


{% endblock %}

forum/templates/forum/append.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
<div class="panel panel-default">
	<div class="panel-heading">
		<p class="panel-title">
			{% blocktrans %}
			添加附言到:{{topic}}  <!-- FIXME: does not rendered correctly -->
			{% endblocktrans %}
		</p>
	</div>
	<div class="panel-body">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
		{% endif %}
		<form class="form" action="{% url 'add_appendix' topic.id%}" method="post">
			{% csrf_token %}
			<div class="form-group ">
				<label class="sr-only" for="content">内容</label>
				<textarea placeholder="内容"  class="form-control" id="content" name="content"></textarea>
			</div>
			<div class="form-submit text-right">
				<a class="btn btn-default" id="pre-btn">预览</a>
				<button class="btn btn-info" type="submit" id="submit">
					提交
				</button>
			</div>
		</form>
		<div class="previewer">

		</div>
	</div>
</div><!--end reply panel-->
{% endblock %}
{% block right %}
{% include 'node-info.html' %}
{% include 'user-panel.html' %}
{% include 'node.html' %}
{% include 'links.html' %}
{% endblock %}
{% block footer_ext %}
<script src="{{STATIC_URL}}js/previewer.js"></script>
{% endblock %}

forum/templates/forum/create-topic.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
<div class="panel panel-default">
    <div class="panel-heading title-breadcrumb">
        <a href="{% url 'index' %}">主页</a>
        <span><a href="{% url 'node_view' node.id%}">{{node.title}}</a></span>
        <span>{新话题</span>
    </div>
    <div class="panel-body">
    	{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
		{% endif %}
        {% if request.user.is_authenticated %}
        <form class="form" action="{% url 'create_topic' node.id%}" method="post">
            {% csrf_token %}
            <div class="form-group ">
                <label class="sr-only" for="title">标题</label>
                <input placeholder="标题(最长30个字符)" type="text" class="form-control" maxlength=30 id="title" name="title" />
            </div>
            <div class="form-group ">
                <label class="sr-only" for="content">内容</label>
                <textarea placeholder="内容"  class="form-control" id="content" name="content"></textarea>
            </div>
            <div class="form-submit text-right">
                <a class="btn btn-default" id="pre-btn">
                    预览
                </a>
                <button class="btn btn-info" type="submit" id="submit">
                    提交(Ctrl+Enter)
                </button>
            </div>
        </form>
        <div class="previewer">

        </div>
        {% else %}
        <div class="alert alert-info">
            登录后方可发言
        </div>
        <a href="{% url 'signin' %}" class="btn btn-info">登录</a>
        {% endif %}
    </div>
</div><!--end reply panel-->
{% endblock %}
{% block right %}
{% include 'node-info.html' %}
{% include 'user-panel.html' %}
{% include 'node.html' %}
{% include 'links.html' %}
{% endblock %}
{% block footer_ext %}
<script src="{{STATIC_URL}}js/previewer.js"></script>
{% endblock %}

forum/templates/forum/develop.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <title>开发中--EvilFinder</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="{% static 'css/404.css' %}">

    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3551564-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
    <div id="error">
      <a href="{% url 'index' %}">
        <img src="{% static 'image/develop.jpg' %}" alt="404 page not found" id="error404-image" />
      </a>
    </div>
</body>
</html>

forum/templates/forum/edit-topic.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
<div class="panel panel-default">
    <div class="panel-heading">
        <p class="panel-title">
            编辑话题-{{topic.title}}
        </p>
    </div>
    <div class="panel-body">
    	{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
		{% endif %}
        {% if request.user.is_authenticated %}
        <form class="form" action="{% url 'edit_topic' topic.id%}" method="post">
            {% csrf_token %}
            <div class="form-group ">
                <label class="sr-only" for="title">标题</label>
                <input placeholder="标题" value="{{topic.title}}" type="text" class="form-control" id="title" name="title" />
            </div>
            <div class="form-group ">
                <label class="sr-only" for="content">内容</label>
                <textarea placeholder="内容"  class="form-control" id="content" name="content">{{topic.content}}</textarea>
            </div>
            <div class="form-submit text-right">
                <a class="btn btn-default" id="pre-btn">
                    预览
                </a>
                <button class="btn btn-info" type="submit" id="submit">
                    提交(Ctrl+Enter)
                </button>
            </div>
        </form>
        
        <div class="previewer">
        </div>
        {% endif %}
    </div>
</div><!--end reply panel-->
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'links.html' %}
{% endblock %}
{% block footer_ext %}
<script src="{{STATIC_URL}}js/previewer.js"></script>
{% endblock %}

forum/templates/forum/index.html
{% extends 'base-with-sidebar.html' %}
{% block header_ext%}
    <meta name="keywords" content="" />
    <meta name="description" content="" />
{% endblock %}
{% block left %}
{% include 'topic-list.html' %}
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'node.html' %}
{% include 'topic-hot.html' %}
{% include 'links.html' %}
<!--{% include 'stat.html' %}-->
{% endblock %}

forum/templates/forum/node-all.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">节点导航</h3>
    </div>
    <div class="panel-body">
        <div class="panel-body">            
            {% for category,node_list in nodes.items %}
           	<table cellpadding="0" cellspacing="0" border="0">
				<tbody>
					<tr>
						<td align="right" width="60">{{category}}</td>
						<td style="line-height: 200%; padding-left: 10px;">
							{% for node in node_list %}
							<span class="label label-default list-meta-node">
							<a href="{% url 'node_view' node.id %}">
								{{ node.title }}
							</a>
							</span>
							{% endfor %}
						</td>
					</tr>
				</tbody>
			</table>
			{% endfor %}
</div>
    </div>
</div>
{% endblock %}
{% block right %}
{% include 'user-panel.html' %}
{% include 'node.html' %}
{% include 'links.html' %}
{% endblock %}
{% block footer_ext %}



{% endblock %}

forum/templates/forum/node-sort.html
{% extends 'base-with-sidebar.html' %}
{% load humanize %}
{% load pagination_tags %}

{% block left %}

<div class="panel panel-default" style="line-height:12px">
	<div class="panel-heading title-breadcrumb">
        话题分类
	</div>
	{% if not node_list %}
	<div class="panel-body">
		<div class="alert alert-info">
			话题分类列表为空
		</div>
	</div>
	{% endif %}
	<ul class="list-group">
		{% autopaginate node_list 12 %}   
		{% for t in node_list %}
		<div class="list-group-item list-topic-item" id="node-{{t.id}}">
			<div class="row ">
				<a href="{% url 'node_view' t.id %}" class="col-md-1 col-xs-2 col-sm-2 node-icon-span" style="background-color:{{i}}"><span>{{ t.id }}</span></a>
				<div class="col-xs-9 col-md-10 col-sm-9">
					<h3 class="list-post-title" id="node-list-line"><a href="{% url 'node_view' t.id %}">{{t.title}}</a></h3>
                    <a class="nodedescription">{{t.description}}</a>
				</div>
				<div class="col-xs-1 col-sm-1">
					<span class="badge pull-right list-reply-count hidden-xs" style="margin-top:17px">{{ t.count }}</span>
				</div>
			</div>
		</div>
		{% endfor %}
	</ul>
	<div class="panel-footer">
		{% paginate %}
	</div>
</div>

{% endblock %}

{% block right %}
{% include 'user-panel.html' %}
{% include 'links.html' %}
{% include 'stat.html' %}
{% endblock %}

forum/templates/forum/node-view.html
{% extends 'base-with-sidebar.html' %}
{% block left %}
{% include 'topic-list.html' %}
{% endblock %}
{% block right %}
{% include 'node-info.html' %}
{% include 'user-panel.html' %}
{% include 'node.html' %}
{% include 'links.html' %}
{% endblock %}
{% block footer_ext %}
<script> var host = "{{request.META.HTTP_HOST}}";var page = "{{page}}"; </script>
<script>
    function next_page(){
        window.location = 'http://' + host + "{% url 'node_view' node.id %}" + "?page=" + (parseInt(page) + 1);
    }
    function prev_page(){
        window.location = 'http://' + host + "{% url 'node_view' node.id %}" + "?page=" + (parseInt(page) - 1);
    }
</script>
{% endblock %}

forum/templates/forum/topic.html
{% extends 'base-with-sidebar.html' %}
{% load i18n %}
{% block left %}
{% load humanize %}
{% load pagination_tags %}
{% load settingsvalue %}
<div class="panel panel-default">
	<div class="topic-heading panel-heading">
		<div class="row">
			<a href="{% url 'user_info' topic.user.id %}" class="col-md-1 pull-right"><img title="{{topic.user.profile.username}}" class="avatar-middle pull-right" src="{{topic.user.profile.avatar.middle}}"></a>
			<div class="col-md-10">
				<p class="topic-breadcrumb">
                        <a href="{% url 'index' %}">{% conf_value "logoname" %}</a>  ›   <a href="{% url 'node_view' topic.node.id  %}">{{topic.node.title}}</a>
                </p>
				<h3 class="list-post-title-in-topic">{{topic.title}}</h3>
				<p class="list-meta">
					<span class="label label-default list-meta-node"><a href="{% url 'node_view' topic.node.id %}">{{topic.node.title}}</a></span>
					<span class="list-count">{{topic.click}}</span>
					<span class="list-time">{{topic.time_created | naturaltime}}</span>
					<span class="list-username"><a href="{% url 'user_info' topic.user.id %}">{{topic.user.profile.username}}</a></span>
					{% if request.user == topic.user%}
					<a class="label-success label" href="{% url 'add_appendix' topic.id %}">添加附言</a>
					{% endif %}
					{% if request.user.is_superuser or topic.user == request.user %}
					<a class="label-warning label" href="{% url 'edit_topic' topic.id %}">编辑</a>
					<a class="label-danger label" href="{% url 'delete_topic' topic.id %}">删除</a>
					{% endif %}
				</p>
			</div>
		</div>
	</div>
	<div class="panel-body">
		{{topic.content_rendered | safe}}
	</div>
	{% if topic.appendix_set.all %}
	<ul class="list-group">
		{% for a in topic.appendix_set.all %}
		<div class="list-group-item list-appendix-item">
			<p class="appendix-meta">
				{% blocktrans with number=forloop.counter %}appendix {{number}}{% endblocktrans %} {{a.time_created|naturaltime}}
			</p>
			{{a.content_rendered | safe}}
		</div>
		{% endfor %}
	</ul>
	{% endif %}
</div><!--end content panel-->

<div class="panel panel-default">
	<div class="panel-heading">
		<p class="panel-title">
			{% if topic.reply_count %}
			{% blocktrans count reply_count=topic.reply_count %}
			{{reply_count}} reply
			{% plural %}
			{{reply_count}} replies
			{% endblocktrans %}
			{% else %}
			没有回复
			{% endif %}
		</p>
	</div>
	{% if topic.reply_count != 0 %}
	<ul class="list-group">
		{% autopaginate posts 30 %}
		{% for r in posts %}
		<div class="list-group-item list-topic-item" id="post-{{r.id}}">
			<div class="row ">
				<a href="{% url 'user_info' r.user.id %}" class="col-md-1"><img title="{{r.user.profile.username}}" class="avatar-middle" src="{{r.user.profile.avatar.middle}}"></a>
				<div class="col-xs-11">
					<div class="row">
						<div class="reply-author col-sm-10">
							<a href="{% url 'user_info' r.user.id %}">{{r.user.profile.username}}</a>
							<span class="list-time">{{r.time_created | naturaltime}}</span>
							{% if request.user.is_superuser %}
							<a class="delete" href="{% url 'delete_post' r.id%}">删除</a>
							{% endif %}
						</div>
						<div class="col-sm-2">
							{% if request.user.is_authenticated %}
							<a href="#create_reply" data-user="{{r.user.username}}" class="label-info label pull-right reply-btn">reply</a>
							{% endif %}
						</div>
					</div>
					<div class="row">
						<div class="reply-content col-md-12">
							{{r.content_rendered | safe}}
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</ul>
	<div class="panel-footer">
		{% paginate %}
	</div>
	{% else %}
	<div class="panel-body">
		<div class="alert alert-info">
			没有回复
		</div>
	</div>
	{% endif %}
</div><!--end reply panel-->

<div class="panel panel-default" id="create_reply">
	<div class="panel-heading">
		<p class="panel-title">
			回复
		</p>
	</div>
	<div class="panel-body">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
			<p class="text-{{ message.tags }}">
				{{ message }}
			</p>
			{% endfor %}
		</div>
		{% endif %}
		{% if request.user.is_authenticated %}
		<form class="form" action="{% url 'create_reply' topic.id%}" method="post">
			{% csrf_token %}
			<div class="form-group ">
				<label class="sr-only" for="content">内容</label>
				<textarea class="form-control" id="content" name="content"></textarea>
			</div>

			<div class="form-submit text-right">
				<a class="btn btn-default" id="pre-btn"> 预览 </a>
				<button class="btn btn-info" type="submit" id="submit">
					提交(Ctrl+Enter)
				</button>
			</div>
		</form>
		<div class="previewer">

		</div>
		{% else %}
		<div class="alert alert-info">
			回复前请先登录
		</div>
		<a href="{% url 'signin' %}" class="btn btn-info">登录</a>
		{% endif %}
	</div>

</div><!--end reply panel-->
{% endblock %}
{% block right %}
{% include 'node-info.html' %}
{% include 'user-panel.html' %}
{% include 'node.html' %}
{% include 'links.html' %}
{% endblock %}
{% block footer_ext %}
<script src="{{STATIC_URL}}js/previewer.js"></script>
<script src="{{STATIC_URL}}js/mention.js"></script>
{% endblock %}